[workspace]
members = [ "fluent-static","fluent-static-generate"]
resolver = "2"

exclude = ["examples"]

[workspace.package]
version = "0.1.0"
edition = "2021"

[workspace.dependencies]
fluent-syntax = "0.11"
fluent-bundle = "0.15"
quote = "1"
syn = "1"
proc-macro2 = "1"
thiserror = "1"
convert_case = "0.6"
unic-langid = { version = "0.9", features = ["unic-langid-macros"] }
once_cell = "1"
accept-language = "3.1"

fluent-static-generate = { version = "0.1.0", path = "fluent-static-generate" }
