[workspace]
members = ["simple"]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2021"

[workspace.dependencies]
fluent-static = { version = "0.1.0", path = "../fluent-static" }
fluent-static-codegen = { version = "0.1.0", path = "../fluent-static-codegen" }
