[package]
name = "example"
version = "0.1.0"
edition = "2021"

[dependencies]
fluent-static = { path = "../fluent-static" }

[build-dependencies]
fluent-static-codegen = { path = "../fluent-static-codegen" }
